//global
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const SET_FORM_DEFAULT_VALUES = 'SET_FORM_DEFAULT_VALUES';

// auth
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_STARTED = 'REGISTER_STARTED';
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';

// categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCEEDED = 'GET_CATEGORIES_SUCCEEDED';

// properties
export const GET_PROPERTIES = 'GET_PROPERTIES';
export const GET_PROPERTIES_SUCCEEDED = 'GET_PROPERTIES_SUCCEEDED';

export const CREATE_PROPERTY = 'CREATE_PROPERTY';
export const CREATE_PROPERTY_SUCCEEDED = 'CREATE_PROPERTY_SUCCEEDED';

export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const UPDATE_PROPERTY_SUCCEEDED = 'UPDATE_PROPERTY_SUCCEEDED';

export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const DELETE_PROPERTY_SUCCEEDED = 'DELETE_PROPERTY_SUCCEEDED';

// Property Attributes
export const GET_PROPERTY_ATTRIBUTES = 'GET_PROPERTY_ATTRIBUTES';
export const GET_PROPERTY_ATTRIBUTES_SUCCEEDED = 'GET_PROPERTY_ATTRIBUTES_SUCCEEDED';

export const CREATE_PROPERTY_ATTRIBUTE = 'CREATE_PROPERTY_ATTRIBUTE';
export const CREATE_PROPERTY_ATTRIBUTE_SUCCEEDED = 'CREATE_PROPERTY_ATTRIBUTE_SUCCEEDED';

export const UPDATE_PROPERTY_ATTRIBUTE = 'UPDATE_PROPERTY_ATTRIBUTE';
export const UPDATE_PROPERTY_ATTRIBUTE_SUCCEEDED = 'UPDATE_PROPERTY_ATTRIBUTE_SUCCEEDED';

export const DELETE_PROPERTY_ATTRIBUTE = 'DELETE_PROPERTY_ATTRIBUTE';
export const DELETE_PROPERTY_ATTRIBUTE_SUCCEEDED = 'DELETE_PROPERTY_ATTRIBUTE_SUCCEEDED';

export const SET_SHOW_ATTRIBUTES = 'SET_SHOW_ATTRIBUTES';

export const GET_PROPERTY_ATTRIBUTES_BY_PROPERTY_ID = 'GET_PROPERTY_ATTRIBUTES_BY_PROPERTY_ID';
export const GET_PROPERTY_ATTRIBUTES_BY_PROPERTY_ID_SUCCEEDED = 'GET_PROPERTY_ATTRIBUTES_BY_PROPERTY_ID_SUCCEEDED';

export const RESET_ATTRIBUTES_BY_PROPERTY_ID = 'RESET_ATTRIBUTES_BY_PROPERTY_ID';
export const ADD_ATTRIBUTES_BY_PROPERTY_ID = 'ADD_ATTRIBUTES_BY_PROPERTY_ID';
export const REMOVE_ATTRIBUTES_BY_PROPERTY_ID = 'REMOVE_ATTRIBUTES_BY_PROPERTY_ID';