//global
export const UPDATE_LOADING = 'UPDATE_LOADING';

// auth
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_STARTED = 'REGISTER_STARTED';
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';

// categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCEEDED = 'GET_CATEGORIES_SUCCEEDED';
